### ISSUE TITLE
Handling references conditionally

### ISSUE THREAD

**Issue by nkuek** [FormidableLabs/groqd#104]
If I have an array of both references and non-references, Sanity's GROQ documentation mentions a way to [conditionally return the referenced object](https://www.sanity.io/docs/query-cheat-sheet#a1da4a3b2adc) using `@->`. I have tried using a conditional selector using `.select` as follows:

```typescript
q('*')
  .filter(_type == "someType")
  .grab({
    maybeReference: q('maybeReference').filter().select({
      "_type == 'nonreference': {
        ...
      },
     "_type == 'reference': {
       // unsure how to deref
     }
  })
})
```
but have been unsuccessful in grabbing the de-referenced object.

Is there a way to conditionally de-reference selections yet?

**Comment by nkuek** [comment]
After banging my head against the wall a bunch, I figured out that you can recreate the `@->` selector mentioned in the Sanity docs by doing
```typescript
q('@').deref()
```
so the full context would be
```typescript
q('*')
  .filter(_type == "someType")
  .grab({
    maybeReference: q('maybeReference').filter().select({
      "_type == 'nonreference': {
        ...
      },
     "_type == 'reference': q('@').deref().grab({
        // referenced fields here
     })
  })
})

**Comment by DanProudfoot** [comment]
Thank you so much, what a weird way of doing things, but glad it works!
