### ISSUE TITLE
Is this the correct way to handle nested arrays/objects?

### ISSUE THREAD

**Issue by Zylvian** [FormidableLabs/groqd#105]
Looking into groqd, wanted to test it first on a navbar. The syntax looks a bit messy with the way I've done it, curious if this was the way to go about it.

```js
const navbarSelection = {
        mainNavigationGroups: q.array(q.object({
            navItem: q.object({
                text: q.string(),
                navigationItemUrl: q.object({
                    externalUrl: q.string()
                })
            }),
            subNavigationItems: q.array(q.object({
                    text: q.string()
                }
            ))
        }))
    }

const query = q("*", {isArray: true})
        .filter("_type == 'navbar'")
        .grab$({
            _id: q.string(),
            ...navbarSelection
        });
        
```

There aren't a lot of in-depth examples in the docs, so I figured I'd ask here, thanks!

**Comment by JohnGemstone** [comment]
Yeah I think a common misconception is how `q.object` and `q.array` work. They are basic zod types and won't actually affect how the query is built. Instead you should use/chain the `.grab` and `.filter` functions respectively.
I put together an example here if you want to take a look.
https://github.com/FormidableLabs/groqd/issues/88#issuecomment-1463021786

Hope this helps!

**Comment by gksander** [comment]
This is a fantastic question. What you have _works_, but might be over-fetching data (which might be fine based on your scenario).

By using the `q.array`/`q.object` approach, you're doing a somewhat coarse query and then letting Zod filter out the stuff you want once the data is fetched. Like @JohnGemstone mentioned, using `.grab` and `.filter` will allow you to be more explicit about what you're fetching.

Here's a quick example. Let's say you have pokemon with some type information on them. You could do something like this:

```ts
q("*").filterByType("pokemon").grab({
  types: q.array(q.object({ name: q.string() }))
})
```

This results in a query of `*[_type == "pokemon"]{types}`, and if the `types` array entities end up with a lot of information besides `name`, you'll be getting all of that data from your network request – and then it'll get filtered out.

You could modify that to something like this:

```ts
q("*").filterByType("pokemon").grab({
  types: q("types").filter().grab({ name: q.string() })
})
```

which results in a query like `*[_type == "pokemon"]{"types": types[]{name}}` which _only_ fetches the name property.

Both will result in an output of the same shape – there's just a difference in granularity of the groq query/fetch.
