### ISSUE TITLE
`q.contentBlock()` assumes `_type` of `block`

### ISSUE THREAD

**Issue by fritz-c** [FormidableLabs/groqd#114]
The `_type` of a `PortableTextBlock` does not necessarily have to be `block`:
https://github.com/portabletext/types/blob/e54eb24f136d8efd51a46c6a190e7c46e79b5380/src/portableText.ts#L24-L26
https://github.com/portabletext/react-portabletext/pull/54#issuecomment-1494724526

The current groqd source validates `q.contentBlock()` with `z.literal("block")`:
https://github.com/FormidableLabs/groqd/blob/5e69051c8f78a39780bbc64e50e1eda2d90f8b4a/packages/groqd/src/contentBlock.ts#L28
but maybe it should be `z.string()` instead.

**Comment by gksander** [comment]
That sounds reasonable. That should be an easy change, I'll try to get that pushed through.
