### ISSUE TITLE
Documentation needed for `q.select()`

### ISSUE THREAD

**Issue by fritz-c** [FormidableLabs/groqd#115]
The `q.select()` API, added in [v0.10.0](https://github.com/FormidableLabs/groqd/releases/tag/v0.10.0), does not yet have any documentation on its usage.

**Comment by gksander** [comment]
@littlemilkstudio how are things going with `q.select`? Feeling confident enough to add docs and make it more publicly visible?

**Comment by littlemilkstudio** [comment]
yea, I can work on some docs around it. Was waiting for the thumbs up to more publicly adopt it.

I have some more opinions on it after working with it a little, but it works well in its current usage and haven't run into any hiccups w/ it thusfar

**Comment by gksander** [comment]
Sick. I'm good with making it official – if it's working for you and the team, it's good with me.

**Comment by littlemilkstudio** [comment]
I guess my only hesitation is that there's some enhancements from the existing `grab({}, conditions)` api, that a user might expect after `select(conditions)` gets documented.

but replacing the conditional implementation of `grab` with the underlying `select` method might not be too bad. I guess the documentation coming before that update might not be a big deal.

**Main enhancements to highlight:**
- type of the conditions arg
```ts
// grab
type Conditions = {
  [condition: string]: Selection
}

// Select
type Conditions = {
  [condition: string]: Selection | [string, zodType] | Query
}
```

- `select` adds the ability to have a `default` condition
- if using `EntityQuery.select(s: BaseQuery | Conditions)` or `ArraQuery.select(s: BaseQuery | Conditions)`, the conditions arg can either be a `BaseQuery | Conditions`, allows us to do stuff like:
```ts
// GROQ: select(...)
const pokeAttributeSelect = q.select({
  '_type == "Charzard"': {
    attack: q.number()
  },
  default: {
    health: q.number()
  }
});

// GROQ: *[_type == "pokemon"]{ attributes{ ...select(...) }  }
const query = q(*).filterByType('pokemon').grab({
  attributes: q('attributes').select(pokeAttributeSelect)
})
```

**Comment by heggemsnes** [comment]
I've started using this feature and find it great, but one use-case I struggle a bit with is this:

```
// GROQ *[_type == "menuConfig"]{
   "menu": menu[]{
     _key,
     ...select(
     // conditional select based on either external link or internal link 
    )
   }
}
```

Just shooting in here that this would be great to have mentioned in the docs.

**Comment by littlemilkstudio** [comment]
@heggemsnes thanks for relaying. will work on some docs for it today.

For the specific case you're referencing, currently the only way to merge other fields w/ a `select` within a projection is through supplying both the `selection` & `conditions` args to the `.grab(selection, conditions)` method

The `q.select(conditions)` method purely maps to GROQ's `select(conditions)` method. Here are the GROQ equivalents for how certain scenarios are interpreted depending on the context you use it in:
```ts
const baseSelect = q.select(/* conditions */)
/*
 * output GROQ
 * ```groq
  select(
    // conditions
  )
*```
*/

const entityLevelSelect = q('someField').select(/* conditions */)
/*
 * output GROQ
 * ```groq
  someField{
    ...select(
      // conditions
    )
  }
*```
*/

const arrayLevelSelect = q('someField').filter().select(/* conditions */)
/*
 * output GROQ
 * ```groq
  someField[]{
    ...select(
      // conditions
    )
  }
*```
*/

```

**Comment by littlemilkstudio** [comment]
@gksander @heggemsnes here's the PR for [select documentation](https://github.com/FormidableLabs/groqd/pull/155)

**Comment by littlemilkstudio** [comment]
Just merged. Documentation can be found [here](https://formidable.com/open-source/groqd/query-building/#select)
