### ISSUE TITLE
I wanna return just one result instead an array?

### ISSUE THREAD

**Issue by williamneves** [FormidableLabs/groqd#199]
I wanna return just one result instead an array, normally I put [0] at the end of the groq query, but how to do with grod?

**Comment by markomitranic** [comment]
@williamneves afaik there is no built in way to do this. There should be.

I use a manual check in my repository level functions, like this:

```ts
function firstResult<T>(results: T[]): T {
  const result = results[0];
  if (!result || results.length !== 1) throw Error("No results found.");
  return result;
}
```

Then later in my repository code:
```ts
/**
 * Fetches a single post object with exact slug match. 
 * Throws if no objects found.
 *
 * @example
 * const post = await getPost();
 * { _id: "123", title: "Lorem Ipsum", slug: "lorem-ipsum" }
 */
export async function getPost(slug: string) {
  const posts = await runQuery(
    q("*")
      .filterByType("post")
      .filter("slug.current == $slug")
      .grab(PostSelection),
    {slug}
  );

  return firstResult(posts);
}
```

**Comment by williamneves** [comment]
I found a way. Just put filter(0) and works. The filter opens a [] so put 0 and done 😀

**Comment by heggemsnes** [comment]
I guess you could do this but, the reccomended would be to do `slice(0)` like this:

```
q("*").filterByType("post").grab({_id: q.string()}).slice(0)
```

**Comment by williamneves** [comment]
But the slice return array with 1 element. Filter (0) get back an object.

**Comment by heggemsnes** [comment]
What version are you using? You can see that the returned data when using slice(0) is a object and not an array with a single item:

https://formidable.com/open-source/groqd/arcade?data=pokemon&code=JYWwDg9gTgLgBAbzlArgOwIooKZQJ5wC%2BcAZlBCHAERgA2AhngObnoAmVA3AFCiSyI4ARyKlylKiwhCOPbqkw58ACm5xhyqgCoqASjVwAdCWC0YuAEJ4AKnjDZNkANbYQENHoOGAzrWABjBwAGfXVDFnoAI2UEA3U0ehBsAC5hHxgoYDQmZV0AGji4ehgYen8nVIBtKkj6b2xDAEESsqcqPLS0FBBI3FyAXQL1Qn1dTiA

**Comment by williamneves** [comment]
Ow. Yeah. Thanks !!!

**Comment by gksander** [comment]
Marking this as resolved, thanks for the help @heggemsnes!
