### ISSUE TITLE
Shaping nested objects in the query

### ISSUE THREAD

**Issue by markomitranic** [FormidableLabs/groqd#200]
Heya folks, thanks for making an awesome abstraction :) 

I can't find any info or examples about shaping nested objects during a query.
For example, I've borrowed the query from our [Arcade](https://formidable.com/open-source/groqd/arcade?data=pokemon&code=JYWwDg9gTgLgBAbzlArgOwIooKZQJ5wC%2BcAZlBCHAERgA2AhngObnoAmVA3AFCiSyI4ARyKlylKiwhCOPbqkw58ACm5xhyqgCoqASjVwAdCWC0YuAEJ4AKnjDZNkANbYQENHoOGAzrWABjBwAGABo4AA59dUMWegAjZQQDdTR6EGwALmEfGChgNCZlXRDk6m8YehhvKiyhQwg4gCtsfxhE0vUqSor-Jxq4AG0qOPpvbEMAQRgevrC6tBQQONwigF0S9XVCYoNt7l1OIA) and edited it so that it contains an object at invented property `stats`, and then I assign values to it by providing every field's path explicitly - `"attack": ["base.Attack", q.number()]`
```ts
  q("*").filterByType("pokemon")
  .grab({
    name: q.string(),
    "stats": q.object({
      "attack": ["base.Attack", q.number()],
      "name-again": ["name", q.string()],
    }),
  })
```

Obviously, this doesn't work :D so, what am I missing?

**Comment by markomitranic** [comment]
The answer was fairly simple actually! We should probably add it to the docs somewhere. I can open a PR?

```ts
  q("*").filterByType("pokemon")
  .grab({
    name: q.string(),
    "stats": q("base")({
      "attack": ["Attack", q.number()],
    }),
  })
```

The only remaining question would be if i could somehow map fields that are outside of `"base"` into the new `"stats"`. Any ideas?

**Comment by heggemsnes** [comment]
Yes, you can do it with an empty "q" like this:

```
  q("*").filterByType("pokemon")
  .grab({
    name: q.string(),
    stats: q("").grab({
      "attack": ["base.Attack", q.number()],
      "name-again": ["name", q.string()],
    }),
  })
```
