### ISSUE TITLE
Children required in contentBlocks

### ISSUE THREAD

**Issue by rafaelderolez** [FormidableLabs/groqd#203]
Hey, I just started using groqd on a small side-project and have had a pretty good experience so far aside from this:

## Error

```
Error: Error parsing:
`result.history.story[2].children`: Required
```

**Are custom types in `q.contentBlock(s)` not supported?**

## Sanity

I have a object with a `block` in Sanity defined as such
```typescript
export const history = {
  name: 'history',
  type: 'object',
  title: 'History',
  fields: [
    defineField({
      name: 'story',
      type: 'array',
      of: [
        { type: 'block' },
        { type: 'figure' },
      ],
    }),
  ],
}
```

## GROQD
I query the content like this:
```typescript
export const homePageQuery = q('*')
  .filter("_type == 'home' && language == $lang")
  .grab({
    history: q.object({
      story: q.contentBlocks(),
    }),
  })
  .slice(0)
```

## Data
And here's the actual data from the same groq query (done via Vision):
```json
{
    "story": [
        {
            "style": "h2",
            "_key": "1681cafcabad",
            "markDefs": [],
            "children": [
                {
                    "_type": "span",
                    "marks": [],
                    "text": "[redacted]",
                    "_key": "0d8483f03c770"
                }
            ],
            "_type": "block"
        },
        {
            "_key": "9308d4e3d265",
            "markDefs": [],
            "children": [
                {
                    "marks": [],
                    "text": "[redacted]",
                    "_key": "3edd606646ae",
                    "_type": "span"
                }
            ],
            "_type": "block",
            "style": "normal"
        },
        // 👇 This one is causing issues 👇
        {
            "_type": "figure",
            "alt": "[redacted]",
            "_key": "b5dfcc8c6f4d",
            "asset": {
                "_ref": "image-[redacted].jpg",
                "_type": "reference"
            }
        }
        // 👆 This one is causing issues 👆
    ]
}
```

**Comment by littlemilkstudio** [comment]
Hey @rafaelderolez yea these are a little tricky. @fritz-c posted a nice solution to this same issue with a codesandbox example [here](https://github.com/FormidableLabs/groqd/issues/91#issuecomment-1502094120)

Applying that answer to what you have above, you'll basically want to make `history` a conditional selection that is `q.contentBlock()` when `_type == "block"` and is a figure selection when `_type == "figure"`. You can read more about conditional selections [here](https://formidable.com/open-source/groqd/query-building#select)

Here's a [groqd arcade example](https://formidable.com/open-source/groqd/arcade/?data=NoKA3iAEkEQPoBcCeAHApjAXLAzgg9gE5IwA0UuBxWko00E99MeSANhtjABYBMZFJvADWaElwCMANgAcEgMYBDAGZKARooAmAptBgBbRYWEARNMpw1gAXXK7Y87gEs2mwmgB2Vwbsb3miKicuCiKXnb%2BeobGltg2EZEwCGgAHgg0MMDumoryyZrWOpGwcKLisAAMmjIALDIAzMoV9fIA7K0VMD5MAL7dkLb98MjoGWps%2BPLCXb0JkH5CpWIZAJz1FTKaNWj1mrxSAKxFQtGm5rG0g-Ywji5unt6RC-4GRsIX8f1CyWkZWWg5PIAwpza5LcoweoAzRSCpSKQ1KSKDCg3TDIIZHChLxfSB9exXNGBUZccaTaaoljIDgZDxEQxsGb0HpzZ56YnBGDKJwAcwAru5jsxFGx0lx-oD8iChuCxgdNKp5DJ5FJlDVtJTFDgcGgxfNcfB3MoMk5DDy0ABaCW5KUAOgAVigeULFiNOUa0O4PPIMP18cyKNYQH1rEA&code=JYWwDg9gTgLgBAbzlArgOwIooKZQJ5wC%2BcAZlBCHAERgA2AhngObnoAmVA3AFCiSyI4ARyKlylKiwhCOPbqkw58ACm5xhygOQAqTQEo1cAHQlgtGLi0B9GHjDY4AXkfUAzjGh4q%2Bw0Zb0AI2UEQ3V1d08ALg1NCPx9EzMLKGU9I1dsWmwAYxhg0LD1TRs7B2dqANoIbIBrb2iAbSoEI1bCKgAaYSNsiDQLfoAhKtrUgF0OgsLi23snFypTJhQobHrEKcK4EvtooSNaYGT6WmVF4GXVqj1Jra36VwyYPa0Hp4T-AIB5NGxrVZImi6%2B3cUGAaCYqQMd0KAHpYXAAO4AC3oFgAbrg4BAYMisaZMmxXHA8BAUEj6P04B5NnCEZ9sWhSBcVg5ZthXLSiLcYWxsCR6ChzNEQjCwlYatg8Ht0jAwRDUjyxTtsI1NFR0K4UGB%2BBYOEDuodjqcNWgtTroHrrhMuepNdrddg2AAVUqNKgqzrdUHgyF6G1iwhKsKEG6GUO%2BVyHbJ-AAMBj0nCAA) with your data and what you might use as the query. Your query will basically end up looking something like this:

```ts
export const homePageQuery = q('*')
  .filter("_type == 'home' && language == $lang")
  .grab({
    history: q("history").grab({
      story: q('story').filter().select({
        '_type == "block"': ["{...}", q.contentBlock()],
        '_type == "figure"': {
          _type: q.literal("figure"),
          asset: q('asset').grabOne('_ref', q.string())
          // whatever other fields you want to
          // grab on figure types
        },
        default: {
          _key: q.string(),
          _type: ['"unsupported"', q.literal("unsupported")],
          unsupportedType: ["_type", q.string()],
        },
      }),
    }),
  })
  .slice(0)
```

**Comment by rafaelderolez** [comment]
@littlemilkstudio thanks for that! I missed your comment and am currently on holiday, will get back to you in 2 weeks. Feel free to close this Issue, your explanation and examples look like they should do the trick 👍🏼

**Comment by gksander** [comment]
Closing this for now, but please re-open if you're still having troubles getting this working!

**Comment by tutods** [comment]
> Hey @rafaelderolez yea these are a little tricky. @fritz-c posted a nice solution to this same issue with a codesandbox example [here](https://github.com/FormidableLabs/groqd/issues/91#issuecomment-1502094120)
> 
> Applying that answer to what you have above, you'll basically want to make `history` a conditional selection that is `q.contentBlock()` when `_type == "block"` and is a figure selection when `_type == "figure"`. You can read more about conditional selections [here](https://formidable.com/open-source/groqd/query-building#select)
> 
> Here's a [groqd arcade example](https://formidable.com/open-source/groqd/arcade/?data=NoKA3iAEkEQPoBcCeAHApjAXLAzgg9gE5IwA0UuBxWko00E99MeSANhtjABYBMZFJvADWaElwCMANgAcEgMYBDAGZKARooAmAptBgBbRYWEARNMpw1gAXXK7Y87gEs2mwmgB2Vwbsb3miKicuCiKXnb%2BeobGltg2EZEwCGgAHgg0MMDumoryyZrWOpGwcKLisAAMmjIALDIAzMoV9fIA7K0VMD5MAL7dkLb98MjoGWps%2BPLCXb0JkH5CpWIZAJz1FTKaNWj1mrxSAKxFQtGm5rG0g-Ywji5unt6RC-4GRsIX8f1CyWkZWWg5PIAwpza5LcoweoAzRSCpSKQ1KSKDCg3TDIIZHChLxfSB9exXNGBUZccaTaaoljIDgZDxEQxsGb0HpzZ56YnBGDKJwAcwAru5jsxFGx0lx-oD8iChuCxgdNKp5DJ5FJlDVtJTFDgcGgxfNcfB3MoMk5DDy0ABaCW5KUAOgAVigeULFiNOUa0O4PPIMP18cyKNYQH1rEA&code=JYWwDg9gTgLgBAbzlArgOwIooKZQJ5wC%2BcAZlBCHAERgA2AhngObnoAmVA3AFCiSyI4ARyKlylKiwhCOPbqkw58ACm5xhygOQAqTQEo1cAHQlgtGLi0B9GHjDY4AXkfUAzjGh4q%2Bw0Zb0AI2UEQ3V1d08ALg1NCPx9EzMLKGU9I1dsWmwAYxhg0LD1TRs7B2dqANoIbIBrb2iAbSoEI1bCKgAaYSNsiDQLfoAhKtrUgF0OgsLi23snFypTJhQobHrEKcK4EvtooSNaYGT6WmVF4GXVqj1Jra36VwyYPa0Hp4T-AIB5NGxrVZImi6%2B3cUGAaCYqQMd0KAHpYXAAO4AC3oFgAbrg4BAYMisaZMmxXHA8BAUEj6P04B5NnCEZ9sWhSBcVg5ZthXLSiLcYWxsCR6ChzNEQjCwlYatg8Ht0jAwRDUjyxTtsI1NFR0K4UGB%2BBYOEDuodjqcNWgtTroHrrhMuepNdrddg2AAVUqNKgqzrdUHgyF6G1iwhKsKEG6GUO%2BVyHbJ-AAMBj0nCAA) with your data and what you might use as the query. Your query will basically end up looking something like this:
> 
> ```ts
> export const homePageQuery = q('*')
>   .filter("_type == 'home' && language == $lang")
>   .grab({
>     history: q("history").grab({
>       story: q('story').filter().select({
>         '_type == "block"': ["{...}", q.contentBlock()],
>         '_type == "figure"': {
>           _type: q.literal("figure"),
>           asset: q('asset').grabOne('_ref', q.string())
>           // whatever other fields you want to
>           // grab on figure types
>         },
>         default: {
>           _key: q.string(),
>           _type: ['"unsupported"', q.literal("unsupported")],
>           unsupportedType: ["_type", q.string()],
>         },
>       }),
>     }),
>   })
>   .slice(0)
> ```

Hi @littlemilkstudio 
I'm facing this error:
<img width="993" alt="image" src="https://github.com/FormidableLabs/groqd/assets/18479474/0adae610-cf22-4e6c-9d08-e1be24fdbe87">

This is my content block query:
```tsx
q('body')
    .filter()
    .select({
      '_type == "block"': ['{...}', q.contentBlock()],
      '_type == "gallery"': [
        `{..., "images": ${imagesListQuery('images').query}}`,
        galleryQuery.schema,
      ],
      '_type == "imageWithAlt"': nullToUndefined(imageWithAltQuery('').schema),
      '_type == "imageWithAltAndCaption"': nullToUndefined(imageWithAltAndCaptionQuery().schema),
      '_type == "quote"': ['{...}', quoteQuery],
      '_type == "relatedPosts"': [
        "{..., 'posts': posts[]->{title,'slug': slug.current, headline}}",
        relatedPostsQuery,
      ],
      '_type == "videoUrlWithCover"': videoUrlWithCoverQuery(''),
      default: {
        _key: q.string(),
        _type: ['"unsupported"', q.literal('unsupported')],
        unsupportedType: ['_type', q.string()],
      },
    })
```

The error appears after adding the `nullToUndefined` on both images queries, but if I remove the `nullToUndefined` on images, the `PortableText` shows me an error where the `_key` of the image is `null` and needs to be `string | undefined`.
Do you have any idea how to fix this?
