### ISSUE TITLE
Looking for a page builder example

### ISSUE THREAD

**Issue by th-km** [FormidableLabs/groqd#209]
Hey, I really like using `groqd`, but I'm struggling to build more advanced queries.

I'm looking to do something like this, where I need to resolve the projections of the different content types:

``` 
content[]{
  _type == 'module.one' => {
   ...
  },
  _type == 'module.two' => {
   ...
  }
}
```

```
const homeQuery = q('*')
  .filterByType('home')
  .slice(0)
  .grab({
    _type: q.string(),
    _id: q.string(),
    title: q.string(),
    slug: q.slug('slug'),
    content: ??
  })
```

What would be super useful in the arcade/playground is to be able to write a `groq` query, and get the corresponding `groqd` queries. Or as an alternative create more examples, maybe inspired by this: https://www.sanity.io/docs/query-cheat-sheet. I'd be happy to contribute to that effort.

**Comment by littlemilkstudio** [comment]
hey @th-km thanks for reaching out. Yea we currently have some resources for this type of functionality. Have you checked out the section in our docs for [Forking Selections](https://formidable.com/open-source/groqd/query-building#fork-a-selection-based-on-a-_type)? I think it might be what you're looking for. 

We also have an arcade example of this type of functionality [here](https://formidable.com/open-source/groqd/arcade?data=pokemon&code=JYWwDg9gTgLgBAbzlArgOwIooKZQJ5wC+cAZlBCHAERgA2AhngObnoAmVA3AFCiSyI4ARyKlylKiwhCOPbqkw58ACm5xhyqgCoqASjVwAdCWC0YuAEJ4AKnjDZNkANbYQENHoPHT5qJrT0INhwwGhwANoA5BYotABG9ADO9ChQkQA0cJEAwgAW9FAg9GhsuJEAup7qhonYtNgAxjDKCAbqAPTtcABi0HAx8UkpUJks9HFwMLnBABIACm1ZAUFwALyr1AMJyalUkQBciIvqAPrAbIdCNTBQoUzKuunHcMvYl4a0wL70tJpbQ7tHs9cmBDuEqNtsIZ5lRMlc0CgQHFcA9yk91OpCOiMZ0en08gUiiVcKMoONJtM4ABBGAwegNJyLSKvNYbKgEwrFUpQPaHVoYjFnC7Ca63ND3IEC9Svd6fb6-dn5TnEnmSqX0Wn0pxgiFJKE0ukM2EihFIlG6NGLLGLXG9KBwH60OAQKa4ODOVzuTINJLwV2UUIwCAOuANFCJIMSdCJFBgfjmNhwWr1JrAdxUSZ2bA2roAd1ypmCUGwdNCdzg4ewJFiITQJGgRRgabC9ftCgAtE2VrQIEwmHdFqUSCkzHznkL3hGxRLsQKZRFIlRo7H49hEx63B4MiK5bgfppl3HoAn3RAXJu9JapRW0DGj7A1wA5QJvBevbdXKd3VFWgyEfS6JwQA) . Our arcade goes shows the output from GROQD -> GROQ so you can see what the resulting GROQD query looks like if that helps.

If neither of those satisfy your initial inquiry I'd be happy to provide further support.

**Comment by th-km** [comment]
Hey @littlemilkstudio thanks for the reply. I did try something based on the forking selection example from the documentation, but it was failing because of the deeply nested structure of my modules. I'm using the query below and it's working as expected so far.

```
const content = q('content').filter().select({
  '_type == "module.one"': moduleOne,
  '_type == "module.two"': moduleTwo
})
```

Thanks again for the help.

**Comment by tutods** [comment]
@th-km any issue using `sanityImage` on `PortableText`?
