### ISSUE TITLE
Support ordering by orderRank field

### ISSUE THREAD

**Issue by yhunko** [FormidableLabs/groqd#213]
According to the [Orderable Document list plugin](https://www.sanity.io/plugins/orderable-document-list) documentation, in order to order by the custom rank, we need to use it like so:

```
*[_type == "category"]|order(orderRank)
```

Which seems to not be supported as of now. Current workaround for now is the following usage:

```
export const getQuickAnswersQuery = q('*')
  .filterByType('quickAnswer')
  .grab(quickAnswerSelection)
  // @ts-ignore
  .order('orderRank');
```

Please correct me if I'm misunderstanding something. And if I'm not, it would be great to add a support.

**Comment by gksander** [comment]
Okay, this should be released in `0.15.9`! Thanks for reporting this!
