### ISSUE TITLE
how to fetch images?

### ISSUE THREAD

**Issue by iduuck** [FormidableLabs/groqd#5]
When I try to construct a `q.grab` with `q.unknown()` or something, I am not able to fetch the image properly.

**Comment by gksander** [comment]
This is a great question! Let me look into this a bit. There isn't out-of-the-box support for images yet, but it would be great to have something like a `q.image()` utility to make fetching images convenient.

**Comment by iduuck** [comment]
That'd be awesome, what I do right now is just use the deep grabbing functionality, because the next.js functions also work with only the ref of the image:

```jsx
// ...
q.grab({
	teaserRef: ["teaser.asset._ref", q.string()],
})
// ...
```

**Comment by iduuck** [comment]
Any progress/action plan here?

**Comment by gksander** [comment]
Sorry for the delay, the last month has been busy. I'm going to prioritize this next on my list and hopefully get started working on it today!

**Comment by iduuck** [comment]
No rush, I am fine with my solution right now, just wanted to check back if I can assist on anything.

**Comment by gksander** [comment]
I've been meaning to tackle this for awhile, so I appreciate the bump on it. I'm chugging along and have a WIP PR at #30, although specifics of that are subject to change as I go!

**Comment by gksander** [comment]
Hi @iduuck – I added in somewhat extensive image support via #30. It does quite a bit more than just grab a `_ref`, but might also work for your situation here!
