### ISSUE TITLE
Add option to makeSafeQueryRunner to use safeParse instead of parse

### ISSUE THREAD

**Issue by heggemsnes** [FormidableLabs/groqd#60]
Would be nice to allow the parse to fail sometimes but still get the results.

Currently developing a multilignual site where the build fails since not all the content is in Sanity yet. Would make debugging a bit easier as well.

**Comment by gksander** [comment]
In the latest version of `groqd`, the `GroqdParseError` that's thrown when parsing fails will contain a `.rawResponse` field that contains the raw, unparsed response. This should hopefully help in this case to inspect the raw response!
