### ISSUE TITLE
Empty object being added by conditional selection

### ISSUE THREAD

**Issue by iduuck** [FormidableLabs/groqd#74]
When you are using conditional selection, the type can also be an empty object, which is wrong, because we are explicitly selecting.

![CleanShot 2023-02-23 at 18 36 44@2x](https://user-images.githubusercontent.com/325241/220985879-0f8b97f9-c72b-4eec-b06d-99ffe17c41e9.png)

**Comment by gksander** [comment]
I _think_ this is the same as #25, definitely something I need to do some more noodling on!

**Comment by iduuck** [comment]
Closing this, because of #25
