### ISSUE TITLE
How to query objects?

### ISSUE THREAD

**Issue by JohnGemstone** [FormidableLabs/groqd#76]
Hey all! I had a stab at querying objects within a document using `q.object` but the query builder doesnt seem to be projecting objects for me.

```ts
export async function getEnvironmentPages() {
  const { query, schema } = q("*")
    .filter("_type == 'environment'")
    .slice(0,2)
    .grab({
      name: q.string(),
      slug: q.slug("slug"),
      // object query below
      headerContent: q.object({
        title: q.string(),
        cta: q.string(),
      }),
    });
  return schema.parse(await fetchFromClient({ query }));
}
```

Resulting query:
`*[_type == 'environment'][0..1]{name, "slug": slug.current, headerContent}`

Expected query:
`*[_type == 'environment'][0..1]{name, "slug": slug.current, headerContent { title, cta }`

Maybe I'm missing a trick but couldn't find anything in the tests.
Any help is appreciated! Love the DX for this.

**Comment by JohnGemstone** [comment]
Ok I figured it out!
```ts
export async function getEnvironmentPages() {
  const { query, schema } = q("*")
    .filter("_type == 'environment'")
    .slice(0,2)
    .grab({
      name: q.string(),
      slug: q.slug("slug"),
      // object query below
      headerContent: q("headerContent")
        .grab({
          title: q.string(),
          cta: q.string(),
       }),
    });
  return schema.parse(await fetchFromClient({ query }));
}
```

**Comment by iduuck** [comment]
Can you please close the issue, if this is not an issue anymore? @JohnGemstone
