### ISSUE TITLE
Idea: Switching to a monorepo, so that we can add "sub-packages"

### ISSUE THREAD

**Issue by iduuck** [FormidableLabs/groqd#77]
Hello guys, 
I recently implemented the new [table plugin](https://www.sanity.io/plugins/sanity-table). It would be awesome to have some sort of monorepo, so that third-party clients could be implemented without requiring all users to also install this code. Sure this also could be handled through tree-shaking, but since tree-shaking is a little more advanced topic, I find this solution to be the best for all users.

So, we would have a core package `groqd`. And then like sanity does publish sub-packages as `@groqd/table` for example, which offers the correct typings and structures to implement the table easily.

**Comment by gksander** [comment]
I like this idea. I've got an idea or two for Sanity plug-ins as well, and figured we'd eventually need to migrate to some sort of workspace setup. Shouldn't be terrible to do, I think the biggest lift will be updating our changeset configuration - but we've got some good examples of that here at formidable.

**Comment by gksander** [comment]
Closed via #107, we're good to start adding additional packages 🥳
