### ISSUE TITLE
Safari Bug: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by iduuck** [FormidableLabs/groqd#8]
Hello, I got an error on safari browsers (including mobile safari) and I nailed it down to the **creation of the safe query runner**.

I am seeing the following error:

```
SyntaxError: Invalid regular expression: invalid group specifier name
```

**Comment by gksander** [comment]
Thanks for reporting, I'll take a peak. Interestingly, the `makeSafeQueryRunner` looks like this:

```ts
export const makeSafeQueryRunner =
  (fn: QueryExecutor) =>
  <T extends BaseType>({
    query,
    schema,
  }: QueryResult<T>): Promise<z.infer<T>> =>
    fn(query).then((res) => schema.parse(res));
```

There aren't any regular expressions involved, and it's a pretty simple implementation. I'll peak a little bit deeper to see if I can diagnose what's going on!

**Comment by iduuck** [comment]
Yeah, I already checked the source code, and saw that the lib didn't feature any regular expression. I immediately noticed, that zod is using some regular expressions under the hood, but don't know, why the `makeSafeQueryRunner` import is breaking Safari.

**Comment by iduuck** [comment]
Just saw those 2 issues/prs on the zod repo: https://github.com/colinhacks/zod/issues/1668 https://github.com/colinhacks/zod/pull/1683

Seems like `groqd` needs to update to a reverted version: 3.20.2
